on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false  # Not for (local) pull_requests
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full history
    - run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - run: git push --force --all https://${{ secrets.GITLAB_INF_TOKEN }}@gitlab.inf.ethz.ch/OU-ISG/yac-vays/docs.git
    - run: git push --force --tags https://${{ secrets.GITLAB_INF_TOKEN }}@gitlab.inf.ethz.ch/OU-ISG/yac-vays/docs.git
